FROM rust:1.66-slim-buster as builder
RUN apt-get -y update && apt-get install -y cmake g++
WORKDIR /usr/src
COPY api_server api_server/
COPY event_queue event_queue/
COPY consumer consumer/
WORKDIR /usr/src/consumer
RUN cargo install --path .

FROM debian:buster-slim
COPY --from=builder /usr/local/cargo/bin/consumer /usr/local/bin/consumer
CMD ["consumer"]
