- name: Ensure group "allezon" exists
  become: true
  group:
    name: allezon
    state: present
- name: Ensure user "allezon" exists
  become: true
  user:
    name: allezon
    home: /opt/allezon
    state: present
    group: allezon
- name: Create allezon home directory
  become: true
  file:
    path: /opt/allezon
    state: directory
    mode: 0755
    owner: allezon
    group: allezon
