- name: Setup aerospike
  any_errors_fatal: true
  hosts: aerospike
  tasks:
  - name: Install
    include_tasks:
      file: aerospike/aerospike.yaml

- name: Setup api_server
  any_errors_fatal: true
  hosts: api_server
  tasks:
  - name: Setup allezon
    include_tasks:
      file: allezon.yaml
  - name: Copy api_server executable
    become: true
    copy:
      src: api_server/api_server
      dest: /opt/allezon/api_server
      owner: allezon
      group: allezon
      mode: 0744
  - name: Copy api_server config file
    become: true
    template:
      src: api_server/api_server_start.sh.j2
      dest: /opt/allezon/api_server_start.sh
      owner: allezon
      group: allezon
      mode: 0744
  - name: Copy api_server service file
    become: true
    copy:
      src: api_server/api_server.service
      dest: /etc/systemd/system/api_server.service
      owner: root
      group: root
      mode: 0644
  - name: Restart api_server daemon
    become: true
    systemd:
      name: api_server
      state: restarted
  - name: Ensure api_server daemon is enabled
    become: true
    systemd:
      name: api_server
      state: started
      enabled: yes

- name: Setup nginx
  any_errors_fatal: true
  hosts: nginx
  tasks:
  - name: Install
    include_tasks:
      file: nginx/nginx.yaml
