- name: Setup aerospike
  any_errors_fatal: true
  hosts: aerospike
  tasks:
  - name: Install
    include_tasks:
      file: aerospike/aerospike.yaml

- name: Setup kafka
  any_errors_fatal: true
  hosts: kafka
  tasks:
  - name: Install
    include_tasks:
      file: kafka/kafka.yaml

- name: Setup api_server
  any_errors_fatal: true
  hosts: api_server
  tasks:
  - name: Setup allezon
    include_tasks:
      file: allezon.yaml
  - name: Copy api_server executable
    become: true
    copy:
      src: api_server/api_server
      dest: /opt/allezon/api_server
      owner: allezon
      group: allezon
      mode: 0744
  - name: Copy api_server config file
    become: true
    register: service_conf
    template:
      src: api_server/api_server_start.sh.j2
      dest: /opt/allezon/api_server_start.sh
      owner: allezon
      group: allezon
      mode: 0744
  - name: Copy api_server service file
    become: true
    copy:
      src: api_server/api_server.service
      dest: /etc/systemd/system/api_server.service
      owner: root
      group: root
      mode: 0644
  - name: Ensure api_server daemon are enabled
    become: true
    systemd:
      name: api_server
      state: started
      enabled: yes
  - name: Restart api_server daemon on config change
    become: true
    become_user: root
    systemd:
      name: api_server 
      state: restarted
    when: service_conf.changed

- name: Setup consumer
  any_errors_fatal: true
  hosts: consumer
  tasks:
  - name: Setup allezon
    include_tasks:
      file: allezon.yaml
  - name: Copy consumer executable
    become: true
    copy:
      src: consumer/consumer
      dest: /opt/allezon/consumer
      owner: allezon
      group: allezon
      mode: 0744
  - name: Copy consumer config file
    become: true
    register: service_conf
    template:
      src: consumer/consumer_start.sh.j2
      dest: /opt/allezon/consumer_start.sh
      owner: allezon
      group: allezon
      mode: 0744
  - name: Copy consumer service file
    become: true
    copy:
      src: consumer/consumer.service
      dest: /etc/systemd/system/consumer.service
      owner: root
      group: root
      mode: 0644
  - name: Ensure consumer daemon are enabled
    become: true
    systemd:
      name: consumer
      state: started
      enabled: yes
  - name: Restart consumer daemon on config change
    become: true
    become_user: root
    systemd:
      name: consumer 
      state: restarted
    when: service_conf.changed
