name: Basic checks

on: [push, pull_request]

jobs:
  cargo-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --all-targets --all-features
      - name: Test
        run: cargo test --all-targets --all-features
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- --no-deps -D warnings
      - name: Format
        run: cargo fmt --all -- --check
      - name: Docs
        run: cargo doc --document-private-items --no-deps
